// OWNER: D1.
// No barrel file — a single shared lib/types.ts is a guaranteed four-way conflict.

// ─────────────────────────── MONEY ───────────────────────────
// pg returns `numeric` as a STRING and lib/db.ts deliberately leaves it that
// way: parsing money to a float reintroduces exactly the rounding error that
// numeric(14,2) exists to prevent.  Format it for display; never parseFloat it
// and write it back.
export type Money = string

export type QuotationState =
  | 'draft' | 'pending_approval' | 'approved' | 'negotiation'
  | 'confirmed' | 'rejected' | 'cancelled' | 'expired'

export type RiskBand = 'LOW' | 'MEDIUM' | 'HIGH'
export type LineType = 'one_time' | 'recurring'
export type ApprovalLevel = 'sales_manager' | 'finance'
export type ApprovalStatus = 'pending' | 'approved' | 'returned' | 'rejected'

export type Quotation = {
  id: number
  public_id: string
  number: string
  customer_id: number
  owner_user_id: number
  pricelist_id: number | null
  currency_code: string
  state: QuotationState
  subtotal: Money
  discount_total: Money
  tax_total: Money
  grand_total: Money
  margin_total: Money
  risk_score: string
  risk_band: RiskBand
  requires_manager: boolean
  requires_finance: boolean
  /** Increments on any change to commercial terms.  Orphans every approval. */
  version: number
  last_activity_at: string
  submitted_at: string | null
  approved_at: string | null
  confirmed_at: string | null
  created_at: string
}

export type QuotationLine = {
  id: number
  quotation_id: number
  line_no: number
  product_id: number
  variant_id: number | null
  line_type: LineType
  subscription_plan_id: number | null
  qty: string
  unit_price: Money
  unit_cost: Money
  discount_pct: string
  /** Snapshotted at creation: LEAST(tier.max, category.max).  Never re-read. */
  ceiling_pct: string
  tax_pct: string
  // ── generated by Postgres.  Never write these. ──
  over_by_pct: string
  net_amount: Money
  margin_amount: Money
}

export type ApprovalRequest = {
  id: number
  quotation_id: number
  /** The version this approval belongs to.  LAW 1. */
  quotation_version: number
  level: ApprovalLevel
  seq: number
  status: ApprovalStatus
  assigned_to_user_id: number | null
  acted_by_user_id: number | null
  acted_at: string | null
  note: string | null
  created_at: string
}

/** What scoreQuotation() returns and recomputeQuotation() persists. */
export type RiskAssessment = {
  risk_score: number
  risk_band: RiskBand
  requires_manager: boolean
  requires_finance: boolean
}
