// OWNER: D2.  Client-side invoice PDF (PS §8 deliverables).
//
// jspdf and jspdf-autotable are imported DYNAMICALLY, inside the click
// handler, for two reasons: they are browser-only (jsPDF reaches for `window`),
// and together they are the largest dependency in the project — no screen
// should pay for them until someone actually presses Download.
//
// jspdf-autotable v5 no longer auto-applies itself to the jsPDF prototype
// outside a browser, and the documented v5 usage is the standalone function:
//     autoTable(doc, { … })
// not doc.autoTable({ … }).  The default export IS that function.

export type InvoicePdfData = {
  number: string
  kind: string
  status: string
  issue_date: string
  due_date: string
  currency_code: string
  customer_name: string
  customer_email?: string | null
  order_number?: string | null
  plan_name?: string | null
  amount_total: string
  amount_paid: string
  amount_due: string
  lines: { description: string; qty: string; unit_price: string; amount: string }[]
  payments: { paid_at: string; method: string; reference: string | null; amount: string }[]
}

const symbolFor = (c: string) => (c === 'INR' ? 'Rs.' : c === 'USD' ? '$' : c === 'EUR' ? 'EUR ' : '')

// The built-in PDF fonts are Latin-1 only and have no glyph for ₹ — it renders
// as a blank box.  "Rs." is the honest fallback; embedding a Unicode font
// would add ~400 KB for one character.
const fmt = (v: string | number, c: string) =>
  symbolFor(c) + Number(v).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export async function downloadInvoicePdf(inv: InvoicePdfData) {
  const [{ jsPDF }, autoTableMod] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const autoTable = autoTableMod.default

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const cur = inv.currency_code

  doc.setFontSize(18)
  doc.text('DealFlow360', 40, 50)
  doc.setFontSize(10)
  doc.setTextColor(110)
  doc.text('Invoice', 40, 66)

  doc.setTextColor(20)
  doc.setFontSize(14)
  doc.text(inv.number, 400, 50)
  doc.setFontSize(10)
  doc.setTextColor(110)
  doc.text(`${inv.kind === 'one_time' ? 'One-time' : 'Recurring'} · ${inv.status}`, 400, 66)

  doc.setTextColor(20)
  doc.setFontSize(10)
  doc.text(`Bill to: ${inv.customer_name}`, 40, 100)
  if (inv.customer_email) doc.text(inv.customer_email, 40, 114)
  doc.text(`Issued ${inv.issue_date?.slice(0, 10)}`, 400, 100)
  doc.text(`Due ${inv.due_date?.slice(0, 10)}`, 400, 114)
  if (inv.order_number) doc.text(`Order ${inv.order_number}`, 400, 128)
  if (inv.plan_name) doc.text(`Plan ${inv.plan_name}`, 400, 128)

  autoTable(doc, {
    startY: 150,
    head: [['Description', 'Qty', 'Unit price', 'Amount']],
    body: inv.lines.map((l) => [
      l.description,
      String(Number(l.qty)),
      fmt(l.unit_price, cur),
      fmt(l.amount, cur),
    ]),
    theme: 'striped',
    headStyles: { fillColor: [15, 23, 42] },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
  })

  // `lastAutoTable` is set on the doc by the plugin after each table.
  let y = ((doc as any).lastAutoTable?.finalY ?? 150) + 24

  autoTable(doc, {
    startY: y,
    body: [
      ['Total', fmt(inv.amount_total, cur)],
      ['Paid', fmt(inv.amount_paid, cur)],
      ['Due', fmt(inv.amount_due, cur)],
    ],
    theme: 'plain',
    styles: { fontStyle: 'bold' },
    columnStyles: { 0: { cellWidth: 380 }, 1: { halign: 'right' } },
  })

  if (inv.payments.length > 0) {
    y = ((doc as any).lastAutoTable?.finalY ?? y) + 24
    autoTable(doc, {
      startY: y,
      head: [['Paid at', 'Method', 'Reference', 'Amount']],
      body: inv.payments.map((p) => [
        String(p.paid_at).slice(0, 10),
        p.method,
        p.reference ?? '—',
        fmt(p.amount, cur),
      ]),
      theme: 'grid',
      headStyles: { fillColor: [71, 85, 105] },
      columnStyles: { 3: { halign: 'right' } },
    })
  }

  doc.setFontSize(8)
  doc.setTextColor(140)
  doc.text(
    'Generated by DealFlow360. Status is derived from recorded payments, never set by hand.',
    40,
    doc.internal.pageSize.getHeight() - 30,
  )

  doc.save(`${inv.number}.pdf`)
}
